---
title: "Static dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)

library(tidyverse)
```

Column {data-width=650}
-----------------------------------------------------------------------

### importing url

```{r}
data_file = "https://data.sanjoseca.gov/dataset/918fb7f0-60c0-484e-b31c-334d1ec74e92/resource/15408d78-9734-4ea1-b3e5-a0f99568dd9b/download/crashdata2021-present.csv"

vehicle_data <- read_csv(url(data_file))


vehicle_data$total_injuries = vehicle_data$MinorInjuries + vehicle_data$ModerateInjuries + vehicle_data$SevereInjuries + vehicle_data$FatalInjuries

head(vehicle_data)
dim(vehicle_data)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart Injury Distribution

```{r}
ggplot(data = vehicle_data) + geom_histogram(mapping = aes(x= total_injuries), binwidth = 1)
```

### weather Distribution

```{r}
ggplot(data = vehicle_data) + geom_bar(mapping = aes(x = Weather))
```





### time of day and light visibility level distribution

```{r}
ggplot(data = vehicle_data) + geom_bar(mapping = aes(x = Lighting)) + theme(axis.text.x = element_text(angle = 45, hjust=1))

```


### Road surface distribution

```{r}
ggplot(data = vehicle_data) + geom_bar(mapping = aes(x = RoadwaySurface))

```
















